package net.mnm.src.main;

import java.util.Arrays;

import net.minecraftforge.common.DimensionManager;
import net.minecraftforge.common.MinecraftForge;
import net.mnm.src.event.MNMEventsHandler;
import net.mnm.src.gui.MNMIngameGui;
import net.mnm.src.packet.PacketHandler;
import net.mnm.src.proxy.CommonProxy;
import net.mnm.src.recipe.MNMFunctions;
import net.mnm.src.world.WorldProviderOlympus;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkMod;

@Mod(modid = Util.MOD_ID, name = Util.MOD_NAME, version = Util.VERSION)
@NetworkMod(clientSideRequired = true, serverSideRequired = false, channels={"mnm"}, packetHandler = PacketHandler.class)
public class MythsNMagic
{
	@Instance(Util.MOD_ID)
	public static MythsNMagic instance = new MythsNMagic();

	@SidedProxy(clientSide = "net.mnm.src.proxy.ClientProxy", serverSide = "net.mnm.src.proxy.CommonProxy")
	public static CommonProxy proxy = new CommonProxy();
	
	public static Config config;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		proxy.init();
		ModMetadata data = event.getModMetadata();
		data.autogenerated = false;
		data.modId = Util.MOD_ID;
		data.name = Util.MOD_NAME;
		data.version = Util.VERSION;
		data.url = "Website?";
		data.authorList = Arrays.asList(new String[] { "Madcrazydrumma", "UltimateSpartan" });
		data.description = Util.MOD_NAME + " is a Minecraft mod that will ...";
		config.init(event.getSuggestedConfigurationFile());
		MNMItems.addItems();
		MNMBlocks.addBlocks();
		MNMFunctions.addRecipes();
		MNMFunctions.addEnchantments();
	}

	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		MinecraftForge.EVENT_BUS.register(new MNMIngameGui());
		MinecraftForge.EVENT_BUS.register(new MNMEventsHandler());
		DimensionManager.registerProviderType(Util.olympusID, WorldProviderOlympus.class, true);
		DimensionManager.registerDimension(Util.olympusID, Util.olympusID);
	}

	@EventHandler
	public void postInit(FMLPostInitializationEvent event)
	{
		config.initPost();
	}
}